# Podfile for SecureFace iOS
# Targets iOS 12.0+ as per NHAI Hackathon requirement

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
prepare_react_native_project!

# Flipper disabled for hackathon builds (reduce binary size)
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SecureFace' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes for JS engine (faster startup, smaller bundle)
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Camera with MLKit face detection
  pod 'RNCamera', :path => '../node_modules/react-native-camera', :subspecs => [
    'FaceDetectorMLKit'
  ]

  target 'SecureFaceTests' do
    inherit! :complete
    # Add test pods here
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    # Set deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
